import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./states/provider";
import { Toaster } from "sonner"; // ✅ import Toaster

const geistSans = Geist( {
  variable: "--font-geist-sans",
  subsets: ["latin"],
} );

const geistMono = Geist_Mono( {
  variable: "--font-geist-mono",
  subsets: ["latin"],
} );

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout( {
  children,
}: Readonly<{
  children: React.ReactNode;
}> )
{
  return (
    <html lang="en">
      <body className={ `${ geistSans.variable } ${ geistMono.variable } antialiased` }>
        <ReduxProvider>
          { children }
          <Toaster richColors position="top-center" />
          {/* ✅ Tambahkan Toaster sekali di root */ }
        </ReduxProvider>
      </body>
    </html>
  );
}
